# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files and configuration
COPY package.json package-lock.json tsconfig.json facilities.json travel-bff.yaml ./

# Copy source files
COPY src ./src

# Install dependencies and build
RUN npm ci && npm run build

# Default command to run the MCP server
CMD ["node", "build/index.js"]
